# Generated by Django 6.0.5 on 2026-06-23 15:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AtencionCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('tipo', models.CharField(choices=[('pregunta', 'Pregunta'), ('queja', 'Queja'), ('reclamo', 'Reclamo'), ('sugerencia', 'Sugerencia'), ('soporte', 'Soporte')], max_length=20)),
                ('mensaje', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloqueo_automatico', models.BooleanField(default=True)),
                ('cierre_automatico', models.CharField(default='10 minutos', max_length=20)),
                ('verificacion_adicional', models.BooleanField(default=False)),
                ('alertas_correo', models.BooleanField(default=True)),
                ('alertas_sonoras', models.BooleanField(default=False)),
                ('actividad_sospechosa', models.BooleanField(default=True)),
                ('guardar_historial', models.BooleanField(default=True)),
                ('actividad_nocturna', models.BooleanField(default=True)),
                ('tiempo_almacenamiento', models.CharField(default='6 meses', max_length=20)),
                ('rol_principal', models.CharField(default='Administrador', max_length=30)),
                ('edicion_usuarios', models.BooleanField(default=True)),
                ('creacion_cuentas', models.BooleanField(default=False)),
                ('modo_oscuro', models.BooleanField(default=False)),
                ('version', models.CharField(default='v1.0.3', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('documento', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=50)),
                ('ciudad', models.CharField(max_length=50)),
                ('consulta', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_ingreso', models.CharField(choices=[('visitante_temporal', 'Visitante temporal'), ('proveedor', 'Proveedor'), ('domiciliario', 'Domiciliario')], max_length=30)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo_documento', models.CharField(choices=[('cc', 'Cédula de ciudadanía'), ('ce', 'Cédula de extranjería'), ('pasaporte', 'Pasaporte'), ('ti', 'Tarjeta de identidad')], max_length=20)),
                ('documento', models.CharField(max_length=30)),
                ('visita_a', models.CharField(max_length=100)),
                ('placa', models.CharField(blank=True, max_length=20, null=True)),
                ('empresa', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha', models.DateField()),
                ('hora_ingreso', models.TimeField()),
                ('hora_salida', models.TimeField(blank=True, null=True)),
                ('estado', models.CharField(default='Dentro', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puerta', models.CharField(max_length=100)),
                ('ip', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Puerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('principal', 'Principal'), ('discapacitados', 'Discapacitados'), ('vehiculos', 'Vehículos')], max_length=20)),
                ('torre', models.CharField(blank=True, choices=[('torre_1', 'Torre 1'), ('torre_2', 'Torre 2'), ('torre_3', 'Torre 3')], max_length=20, null=True)),
                ('estado', models.BooleanField(default=False)),
                ('emergencia', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_usuario', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=200)),
                ('tipo_documento', models.CharField(max_length=50)),
                ('documento', models.CharField(max_length=50, unique=True)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('torre', models.CharField(max_length=50)),
                ('parqueadero', models.CharField(blank=True, default='...', max_length=10, null=True)),
                ('placa', models.CharField(blank=True, default='...', max_length=50, null=True)),
                ('fecha', models.DateField()),
                ('hora_registro', models.TimeField()),
                ('observaciones', models.CharField(blank=True, default='...', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=20)),
                ('tipo', models.CharField(max_length=50)),
                ('mensaje', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TarjetaDesconocida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=100, unique=True)),
                ('intentos_fallidos', models.IntegerField(default=0)),
                ('bloqueada', models.BooleanField(default=False)),
                ('ultima_fecha', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_usuario', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=200)),
                ('tipo_documento', models.CharField(max_length=50)),
                ('documento', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=100)),
                ('torre', models.CharField(max_length=50)),
                ('parqueadero', models.CharField(blank=True, max_length=10, null=True)),
                ('placa', models.CharField(blank=True, max_length=50, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INFO', 'INFO'), ('WARNING', 'WARNING'), ('ERROR', 'ERROR')], max_length=20)),
                ('mensaje', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Paquetes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinatario', models.CharField(max_length=200)),
                ('documento', models.CharField(max_length=50)),
                ('nombre_recibe', models.CharField(max_length=200)),
                ('torre', models.CharField(max_length=50)),
                ('paquete', models.CharField(max_length=50)),
                ('agencia', models.CharField(max_length=200)),
                ('fecha', models.DateField()),
                ('hora_ingreso', models.TimeField()),
                ('hora_entrega', models.TimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Entregado', 'Entregado')], default='Pendiente', max_length=20)),
                ('observaciones', models.CharField(blank=True, default='...', max_length=50, null=True)),
                ('entregado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paquetes_entregados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='perfiles/')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('estado', models.CharField(default='inactivo', max_length=20)),
                ('puerta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='diamond.puerta')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_acceso', models.CharField(choices=[('conjunto', 'Acceso al conjunto'), ('torre', 'Acceso a torre')], max_length=20)),
                ('puerta', models.CharField(blank=True, choices=[('principal', 'Principal'), ('discapacitados', 'Discapacitados'), ('vehiculos', 'Vehículos')], max_length=20, null=True)),
                ('torre', models.CharField(blank=True, choices=[('torre_1', 'Torre 1'), ('torre_2', 'Torre 2'), ('torre_3', 'Torre 3')], max_length=20, null=True)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora_entrada', models.TimeField(auto_now_add=True)),
                ('hora_salida', models.TimeField(blank=True, null=True)),
                ('estado', models.CharField(default='permitido', max_length=400)),
                ('motivo', models.CharField(blank=True, max_length=255, null=True)),
                ('persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diamond.registro')),
            ],
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('activa', models.BooleanField(default=True)),
                ('intentos_fallidos', models.IntegerField(default=0)),
                ('bloqueada', models.BooleanField(default=False)),
                ('puertas', models.ManyToManyField(blank=True, to='diamond.puerta')),
            ],
        ),
        migrations.AddField(
            model_name='registro',
            name='tarjeta',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='diamond.tarjeta'),
        ),
        migrations.CreateModel(
            name='HistorialTarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('asignada', 'Asignada'), ('activada', 'Activada'), ('desactivada', 'Desactivada'), ('cambiada', 'Cambiada'), ('editada', 'Editada')], max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('registro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diamond.registro')),
                ('tarjeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diamond.tarjeta')),
            ],
        ),
    ]
