# Generated by Django 5.2.7 on 2026-02-12 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('documento', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=50)),
                ('ciudad', models.CharField(max_length=50)),
                ('consulta', models.TextField()),
            ],
        ),
    ]
