# Generated by Django 5.2.7 on 2026-02-15 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamond', '0003_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='registro',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='registro',
            name='placa',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
