# Generated by Django 5.2.7 on 2026-02-16 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamond', '0004_alter_registro_email_alter_registro_nombre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_usuario', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=200)),
                ('tipo_documento', models.CharField(max_length=50)),
                ('documento', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=100)),
                ('torre', models.CharField(max_length=50)),
                ('parqueadero', models.CharField(blank=True, max_length=10, null=True)),
                ('placa', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
