# Generated by Django 5.2.8 on 2026-02-25 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamond', '0005_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='hora_salida',
            field=models.TimeField(blank=True, default='...', null=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='parqueadero',
            field=models.CharField(blank=True, default='...', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='placa',
            field=models.CharField(blank=True, default='...', max_length=50, null=True),
        ),
    ]
