# Generated by Django 5.2.8 on 2026-02-25 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamond', '0006_alter_registro_email_alter_registro_hora_salida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='hora_salida',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
