# Generated by Django 5.2.8 on 2026-03-08 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamond', '0008_atencioncliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puerta', models.CharField(max_length=100)),
                ('ip', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=20)),
            ],
        ),
    ]
