# Generated by Django 5.2.8 on 2026-03-12 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamond', '0010_registropacceso'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='REgistropAcceso',
            new_name='RegistroAcceso',
        ),
        migrations.AddField(
            model_name='registro',
            name='tarjeta',
            field=models.CharField(default=1234, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
