# Generated by Django 5.2.8 on 2026-03-12 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamond', '0011_rename_registropacceso_registroacceso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='tarjeta',
            field=models.CharField(max_length=50),
        ),
    ]
