# Generated by Django 5.2.8 on 2026-03-12 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamond', '0012_alter_registro_tarjeta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='tarjeta',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
