# Generated by Django 5.2.8 on 2026-03-12 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diamond', '0013_alter_registro_tarjeta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='tarjeta',
        ),
    ]
