# Generated by Django 5.2.8 on 2026-03-12 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamond', '0014_remove_registro_tarjeta'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='tarjeta',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
