# Generated by Django 5.2.8 on 2026-03-12 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamond', '0015_registro_tarjeta'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroacceso',
            name='tipo_acceso',
            field=models.CharField(choices=[('conjunto', 'Acceso al conjunto'), ('torre', 'Acceso a torre')], default='conjunto', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registroacceso',
            name='torre',
            field=models.CharField(blank=True, choices=[('torre_1', 'Torre 1'), ('torre_2', 'Torre 2'), ('torre_3', 'Torre 3')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='registroacceso',
            name='puerta',
            field=models.CharField(blank=True, choices=[('principal', 'Principal'), ('discapacitados', 'Discapacitados'), ('vehiculos', 'Vehículos')], max_length=20, null=True),
        ),
    ]
