# Generated by Django 5.2.12 on 2026-03-24 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamond', '0016_registroacceso_tipo_acceso_registroacceso_torre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='tarjeta',
            field=models.CharField(default=0, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
