# Generated by Django 5.2.12 on 2026-03-28 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamond', '0017_alter_registro_tarjeta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('torre', models.CharField(max_length=10)),
                ('apartamento', models.CharField(max_length=10)),
                ('tarjeta', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='diamond.tarjeta')),
            ],
        ),
    ]
