# Generated by Django 5.2.12 on 2026-03-30 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamond', '0018_tarjeta_persona'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarjeta',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
