# Generated by Django 5.2.12 on 2026-03-30 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diamond', '0019_tarjeta_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarjeta',
            name='estado',
        ),
    ]
