# Generated by Django 5.2.12 on 2026-03-30 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamond', '0020_remove_tarjeta_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='tarjeta',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='diamond.tarjeta'),
        ),
    ]
