# Generated by Django 5.2.12 on 2026-04-01 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamond', '0021_alter_registro_tarjeta'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialTarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diamond.registro')),
                ('tarjeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diamond.tarjeta')),
            ],
        ),
    ]
