# Generated by Django 5.2.12 on 2026-04-03 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamond', '0022_historialtarjeta'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='Observaciones',
            field=models.CharField(blank=True, default='...', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='onservaciones',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
