# Generated by Django 5.2.12 on 2026-04-03 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diamond', '0023_registro_observaciones_usuario_onservaciones'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registro',
            old_name='Observaciones',
            new_name='observaciones',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='onservaciones',
            new_name='observaciones',
        ),
    ]
