# Generated by Django 5.2.12 on 2026-04-04 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamond', '0024_rename_observaciones_registro_observaciones_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='documento',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
