# Generated by Django 5.2.12 on 2026-04-04 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamond', '0025_alter_registro_documento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paquetes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinatario', models.CharField(max_length=200)),
                ('documento', models.CharField(max_length=50)),
                ('nombre_recibe', models.CharField(max_length=200)),
                ('torre', models.CharField(max_length=50)),
                ('paquete', models.CharField(max_length=50)),
                ('agencia', models.CharField(max_length=200)),
                ('fecha', models.DateField()),
                ('hora_ingreso', models.TimeField()),
                ('hora_entrega', models.TimeField(blank=True, null=True)),
                ('observaciones', models.CharField(blank=True, default='...', max_length=50, null=True)),
            ],
        ),
    ]
