# Generated by Django 5.2.12 on 2026-04-10 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamond', '0026_paquetes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Puerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('principal', 'Principal'), ('discapacitados', 'Discapacitados'), ('vehiculos', 'Vehículos')], max_length=20)),
                ('torre', models.CharField(blank=True, choices=[('torre_1', 'Torre 1'), ('torre_2', 'Torre 2'), ('torre_3', 'Torre 3')], max_length=20, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='puertas',
            field=models.ManyToManyField(blank=True, to='diamond.puerta'),
        ),
    ]
