# Generated by Django 5.2.12 on 2026-04-13 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamond', '0027_puerta_tarjeta_puertas'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialtarjeta',
            name='accion',
            field=models.CharField(default='asignada', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registro',
            name='tarjeta',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='diamond.tarjeta'),
        ),
        migrations.DeleteModel(
            name='Persona',
        ),
    ]
