# Generated by Django 5.2.12 on 2026-04-25 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamond', '0028_historialtarjeta_accion_alter_registro_tarjeta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('estado', models.CharField(max_length=20)),
                ('puerta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='diamond.puerta')),
            ],
        ),
    ]
