# Generated by Django 5.2.12 on 2026-04-28 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamond', '0029_dispositivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='puerta',
            name='emergencia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='puerta',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
