# Generated by Django 5.2.12 on 2026-05-02 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamond', '0031_alter_dispositivo_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroacceso',
            name='estado',
            field=models.CharField(default='permitido', max_length=20),
        ),
    ]
