# Generated by Django 5.2.12 on 2026-05-07 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamond', '0032_registroacceso_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivo',
            name='estado',
            field=models.CharField(default='inactivo', max_length=20),
        ),
        migrations.AlterField(
            model_name='historialtarjeta',
            name='accion',
            field=models.CharField(choices=[('asignada', 'Asignada'), ('activada', 'Activada'), ('desactivada', 'Desactivada'), ('cambiada', 'Cambiada'), ('editada', 'Editada')], max_length=20),
        ),
        migrations.AlterField(
            model_name='historialtarjeta',
            name='registro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diamond.registro'),
        ),
    ]
