# Generated by Django 6.0.5 on 2026-05-14 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamond', '0034_passwordresettoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroacceso',
            name='puerta',
        ),
        migrations.AlterField(
            model_name='registroacceso',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diamond.registro'),
        ),
    ]
