# Generated by Django 6.0.5 on 2026-05-14 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamond', '0035_remove_registroacceso_puerta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroacceso',
            name='puerta',
            field=models.CharField(blank=True, choices=[('principal', 'Principal'), ('discapacitados', 'Discapacitados'), ('vehiculos', 'Vehículos')], max_length=20, null=True),
        ),
    ]
