# Generated by Django 6.0.5 on 2026-05-21 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diamond', '0036_registroacceso_puerta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registro',
            old_name='hora_ingreso',
            new_name='hora_registro',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='hora_salida',
        ),
    ]
