# Generated by Django 6.0.5 on 2026-05-25 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamond', '0037_rename_hora_ingreso_registro_hora_registro_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_ingreso', models.CharField(choices=[('visitante_temporal', 'Visitante temporal'), ('proveedor', 'Proveedor'), ('domiciliario', 'Domiciliario')], max_length=30)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo_documento', models.CharField(choices=[('cc', 'Cédula de ciudadanía'), ('ce', 'Cédula de extranjería'), ('pasaporte', 'Pasaporte'), ('ti', 'Tarjeta de identidad')], max_length=20)),
                ('documento', models.CharField(max_length=30)),
                ('visita_a', models.CharField(max_length=100)),
                ('placa', models.CharField(blank=True, max_length=20, null=True)),
                ('empresa', models.CharField(blank=True, max_length=100, null=True)),
                ('hora_ingreso', models.TimeField()),
                ('hora_salida', models.TimeField(blank=True, null=True)),
                ('estado', models.CharField(default='Dentro', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
