# Generated by Django 6.0.5 on 2026-05-25 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamond', '0038_ingreso'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitanteTemporal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('visitante_temporal', 'Visitante temporal'), ('proveedor', 'Proveedor'), ('domiciliario', 'Domiciliario')], max_length=30)),
                ('nombre', models.CharField(max_length=100)),
                ('documento', models.CharField(max_length=20, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('persona_visita', models.CharField(max_length=100)),
                ('torre', models.CharField(max_length=50)),
                ('motivo', models.TextField()),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora_entrada', models.TimeField()),
                ('hora_salida', models.TimeField(blank=True, null=True)),
                ('estado', models.CharField(default='Dentro', max_length=20)),
            ],
        ),
    ]
