# Generated by Django 6.0.5 on 2026-05-25 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diamond', '0039_visitantetemporal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VisitanteTemporal',
        ),
    ]
