# Generated by Django 6.0.5 on 2026-05-25 23:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamond', '0041_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingreso',
            name='fecha',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='perfil',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/'),
        ),
    ]
