# Generated by Django 6.0.5 on 2026-05-26 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamond', '0042_ingreso_fecha_alter_perfil_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingreso',
            name='fecha',
            field=models.DateField(),
        ),
    ]
