# Generated by Django 6.0.5 on 2026-05-27 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamond', '0044_alter_perfil_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquetes',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Entregado', 'Entregado')], default='Pendiente', max_length=20),
        ),
    ]
