# Generated by Django 6.0.5 on 2026-05-27 00:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamond', '0045_paquetes_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paquetes',
            name='entregado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paquetes_entregados', to=settings.AUTH_USER_MODEL),
        ),
    ]
