# Generated by Django 6.0.5 on 2026-06-02 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamond', '0046_paquetes_entregado_por'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloqueo_automatico', models.BooleanField(default=True)),
                ('cierre_automatico', models.CharField(default='10 minutos', max_length=20)),
                ('verificacion_adicional', models.BooleanField(default=False)),
                ('alertas_correo', models.BooleanField(default=True)),
                ('alertas_sonoras', models.BooleanField(default=False)),
                ('actividad_sospechosa', models.BooleanField(default=True)),
                ('guardar_historial', models.BooleanField(default=True)),
                ('actividad_nocturna', models.BooleanField(default=True)),
                ('tiempo_almacenamiento', models.CharField(default='90 días', max_length=20)),
                ('rol_principal', models.CharField(default='Administrador', max_length=30)),
                ('edicion_usuarios', models.BooleanField(default=True)),
                ('creacion_cuentas', models.BooleanField(default=False)),
                ('modo_oscuro', models.BooleanField(default=False)),
                ('version', models.CharField(default='v1.0.3', max_length=20)),
            ],
        ),
    ]
