# Generated by Django 6.0.5 on 2026-06-02 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamond', '0047_configuracionsistema'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarjeta',
            name='bloqueada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='intentos_fallidos',
            field=models.IntegerField(default=0),
        ),
    ]
