# Generated by Django 6.0.5 on 2026-06-02 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamond', '0048_tarjeta_bloqueada_tarjeta_intentos_fallidos'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroacceso',
            name='motivo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
