# Generated by Django 6.0.5 on 2026-06-05 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamond', '0049_registroacceso_motivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarjetaDesconocida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=100, unique=True)),
                ('intentos_fallidos', models.IntegerField(default=0)),
                ('bloqueada', models.BooleanField(default=False)),
                ('ultima_fecha', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
