# Generated by Django 6.0.5 on 2026-06-10 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamond', '0051_alerta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroacceso',
            name='estado',
            field=models.CharField(default='permitido', max_length=400),
        ),
    ]
