# Generated by Django 6.0.5 on 2026-06-13 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamond', '0052_alter_registroacceso_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionsistema',
            name='tiempo_almacenamiento',
            field=models.CharField(default='6 meses', max_length=20),
        ),
    ]
